import SearchPage from "@/components/Search";
import { updateRecentlyWatched } from "@/redux/reducers/recentlyWatchedReducers";

import Head from "next/head";
import Link from "next/link";
import { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import { SWRConfig } from "swr";

const fetcher = (...args) => fetch(...args).then((res) => res.json());

function Movies() {
  const dispatch = useDispatch();
  const recentlyWatched = useSelector((state) => state.recentlyWatched.items);
  useEffect(() => {
    const storedState = localStorage.getItem("tvShowsState");
    if (storedState) {
      dispatch(updateRecentlyWatched(JSON.parse(storedState)));
    }
  }, []);
  console.log(recentlyWatched);
  return (
    <div>
      <Head>
        <title>Spicy-TV</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#000" />
        <link rel="manifest" href="/manifest.json" />
        <link rel="shortcut icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" href="/apple-icon.png"></link>
      </Head>
      <SearchPage />

      {recentlyWatched && recentlyWatched.length > 0 && (
        <div className="overflow-x-auto mx-auto w-11/12 ">
          <div className="text-3xl text-white mt-4  mb-3">
            Recently Watched TV Shows
          </div>
          <div className=" flex overflow-x-scroll m-1 p-1  scrollbar-hide">
            {recentlyWatched?.map((e) => (
              <Link key={e.tvid} href={`/${e.tvid}`}>
                <div className="relative w-64 h-36 mb-3 mx-2">
                  <div className="absolute inset-0 bg-black opacity-50 rounded-lg" />
                  <img
                    className="object-cover w-full h-full rounded-lg"
                    src={e.episode.img?.hd}
                    alt={`Episode ${e.episode.number}`}
                  />
                  <div className="absolute bottom-0 w-full h-1/3 px-4 ">
                    <h3 className="text-base font-semibold text-white">
                      {e.episode.title}
                    </h3>
                    <p className="text-sm text-gray-400">
                      S{e.episode.season} E{e.episode.episode}
                    </p>
                  </div>
                </div>
              </Link>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

export default function Home() {
  return (
    <SWRConfig
      value={{
        fetcher,
      }}
    >
      <Movies />
    </SWRConfig>
  );
}
