import SearchPage from "@/components/Search";
import Head from "next/head";
import { SWRConfig } from "swr";

const fetcher = (...args) => fetch(...args).then((res) => res.json());

function Movies() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SearchPage />
    </div>
  );
}

export default function Home() {
  return (
    <SWRConfig
      value={{
        fetcher,
      }}
    >
      <Movies />
    </SWRConfig>
  );
}
